#!/bin/bash
case $(cat /etc/issue|cut -f 1 -d ' ') in
    'Arch')    INSTALL() { sudo pacman -S --yes $1; }                                        ;;
    'Ubuntu')  INSTALL() { sudo apt install $1 -y --allow-unauthenticated; }                 ;;
    *)         echo 'Your distribution has not implementd yet, please modify this command'   ;;
esac
if [ `which pip|wc -l` == 0 ];then INSTALL python-pip;fi
sudo pip install -U cheat tldr
