#!/bin/bash
if [ `which wget|wc -l` == 0 ];then sudo apt install -y --allow wget;fi
if [ `which python|wc -l` == 0 ];then sudo apt install -y --allow python;fi

sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"

