#!/bin/bash
set -x
brew tap homebrew/command-not-found
mkdir -p ~/.config/conf.d
echo 'brew command command-not-found-init > /dev/null 2>&1; and . (brew command-not-found-init)'|tee ~/.config/conf.d/homebrew-command-not-found.fish
