#!/bin/bash
case $(cat /etc/issue|cut -f 1 -d ' ') in
    'Arch')    INSTALL() { sudo pacman -S $1; }                                        ;;
    'Ubuntu')  INSTALL() { sudo apt install $1 -y --allow-unauthenticated; }                 ;;
    *)         echo 'Your distribution has not implementd yet, please modify this command'   ;;
esac
if [ `sudo whereis pip3|grep /usr|wc -l` == 0 ];then INSTALL python3-pip;fi
sudo pip3 install --user powerline-status
