#!/bin/bash
wget -nv -O Release.key \
  https://build.opensuse.org/projects/home:manuelschneid3r/public_key
sudo apt-key add - < Release.key
rm Release.key
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_$(cat /etc/issue|cut -f 2 -d ' '|cut -d . -f 1,2)/ /' > /etc/apt/sources.list.d/home:manuelschneid3r.list"
