#!/bin/bash

CONF_PATH=~/.config/fish/conf.d/charles.fish
touch $CONF_PATH

echo '# This is the Charles Scripts Configuration.'> $CONF_PATH

#echo "eval thefuck --alias" >> $CONF_PATH

ANACONDA_PATH=$(locate anaconda3|grep -E 'anaconda3/bin$'|grep $USER)
echo set -x PATH $ANACONDA_PATH \$PATH>> $CONF_PATH

sudo apt install autojump
echo "source /usr/share/autojump/autojump.fish" >> $CONF_PATH

echo "source ~/.shell.d/init.fish" >> $CONF_PATH


#ABBRS
fish -c "abbr ... 'cd ...'"
fish -c "abbr c 'clear; cd'"
fish -c "abbr cl 'cd ..;ls'"
fish -c "abbr eg 'grep -E'"
fish -c "abbr gaa 'git add -A'"
fish -c "abbr gc 'git checkout'"
fish -c "abbr gl 'git l'"
fish -c "abbr gp 'git push'"
fish -c "abbr gpl 'git pull'"
fish -c "abbr gst 'git status'"
fish -c "abbr histg 'history | grep'"
fish -c "abbr i 'ipython --no-confirm-exit --no-banner --pprint -i --pylab=auto'"
fish -c "abbr l 'ls --color=auto'"
fish -c "abbr la 'ls --almost-all --color=auto'"
fish -c "abbr le 'ls --almost-all --color=auto|egrep'"
fish -c "abbr lg 'ls --almost-all --color=auto|grep'"
fish -c "abbr ll 'ls --almost-all -lh --color=auto'"
fish -c "abbr n 'xdg-open .'"
fish -c "abbr o 'xdg-open'"
fish -c "abbr p 'python'"
fish -c "abbr pdb 'python -mpowerline.bindings.pdb'"
fish -c "abbr su 'sudo su'"
fish -c "abbr u 'update'"

