#!/bin/bash
echo "source ~/.shell.d/init.fish" >> ~/.config/fish/config.fish
ANACONDA_PATH=$(locate anaconda3|grep -E 'anaconda3/bin$'|grep $USER)
echo set -x PATH $ANACONDA_PATH \$PATH>> ~/.config/fish/config.fish
