#!/bin/sh
PPA_BACKUP_PATH=/home/ash/Documents/Backup/MyScripts/ppa

for ppa in $@; do
	if [ $ppa ]; then
		sudo apt-add-repository -y $ppa 
		if [ $? = 0 ]; then
			echo $ppa >> $PPA_BACKUP_PATH
		fi
	fi
done

sort -su $PPA_BACKUP_PATH > /tmp/backup4ppa -o $PPA_BACKUP_PATH
sudo rm /etc/apt/sources.list.d/*.save
cat $PPA_BACKUP_PATH
