#!/bin/bash
sudo useradd $1 -s /bin/bash -m 
echo $1 $2 $(date) >> ~/.userscripts/.users
sort -su ~/.userscripts/.users > /tmp/.users -o ~/.userscripts/.users 
sudo cp ~/.userscripts/.users /root/.config
sudo passwd $1 
echo "使用passwd改密码"
