#!/bin/sh
APPS_BACKUP_PATH=/home/ash/Documents/Backup/MyScripts/apps/ubuntu.list

for app in $@;do
	if [ -n "$app" ]; then
		sudo apt install -y $app
		if [ $? = 0 ]; then
			echo $app >> $APPS_BACKUP_PATH
		fi
	fi
done

sort -su $APPS_BACKUP_PATH > /tmp/backuplist4apps -o $APPS_BACKUP_PATH
cat $APPS_BACKUP_PATH
