#!/bin/sh
# configuration
__user__=charles
__backup_path__=/home/charles/Gits/MyScripts

# presettings
__home__=/home/$__user__
b__root__=$__backup_path__/linux
b__etc__=$b__root__/etc
b__home__=$b__root__/home/$__user__

# Make dirs
rm -rf $b__root__
mkdir -p $b__root__ 
mkdir -p $b__etc__
mkdir -p $b__home__
mkdir -p $b__home__/.cache/albert
mkdir -p $b__home__/.config 
mkdir -p $b__home__/.config/sublime-text-3/Packages
mkdir -p $b__home__/.local/share 

# Backups
cp -r /etc/cron.* $b__etc__
cp -r /etc/rc.local $b__etc__
cp -r /etc/hosts.* $b__etc__

cp -r $__home__/.backup $b__home__
cp -r $__home__/.tmux.conf $b__home__
cp -r $__home__/.bash_logout $b__home__
cp -r $__home__/.cache/albert/*.png $b__home__/.cache/albert
cp -r $__home__/.config/fusuma $b__home__/.config
cp -r $__home__/.config/albert.conf $b__home__/.config
cp -r $__home__/.config/sublime-text-3/Packages/User $b__home__/.config/sublime-text-3/Packages
cp -r $__home__/.local/share/albert/ $b__home__/.local/share
cp -r $__home__/.profile $b__home__
cp -r $__home__/.shell* $b__home__
cp -r $__home__/.userscripts $b__home__
cp -r $__home__/.vimconfig.vim $b__home__

# Cleaning useless files
rm $b__etc__/cron.d/anacron
rm $b__etc__/cron.d/php
rm $b__etc__/cron.d/php5
rm $b__etc__/cron.d/.placeholder
rm $b__etc__/cron.d/popularity-contest
rm $b__etc__/cron.d/rsnapshot
rm $b__etc__/cron.d/sysstat
rm $b__etc__/cron.daily/0anacron
rm $b__etc__/cron.daily/apport
rm $b__etc__/cron.daily/apt
rm $b__etc__/cron.daily/apt-compat
rm $b__etc__/cron.daily/aptitude
rm $b__etc__/cron.daily/bsdmainutils
rm $b__etc__/cron.daily/cracklib-runtime
rm $b__etc__/cron.daily/dpkg
rm $b__etc__/cron.daily/exim4-base
rm $b__etc__/cron.daily/google-chrome
rm $b__etc__/cron.daily/google-earth
rm $b__etc__/cron.daily/google-musicmanager
rm $b__etc__/cron.daily/logrotate
rm $b__etc__/cron.daily/man-db
rm $b__etc__/cron.daily/man-db.dpkg-old
rm $b__etc__/cron.daily/mlocate
rm $b__etc__/cron.daily/passwd
rm $b__etc__/cron.daily/.placeholder
rm $b__etc__/cron.daily/popularity-contest
rm $b__etc__/cron.daily/samba
rm $b__etc__/cron.daily/sysstat
rm $b__etc__/cron.daily/update-notifier-common
rm $b__etc__/cron.daily/upstart
rm $b__etc__/cron.daily/upstart.dpkg-old
rm $b__etc__/cron.hourly/.placeholder
rm $b__etc__/cron.monthly/0anacron
rm $b__etc__/cron.monthly/.placeholder
rm $b__etc__/cron.weekly/0anacron
rm $b__etc__/cron.weekly/apt-xapian-index
rm $b__etc__/cron.weekly/fstrim
rm $b__etc__/cron.weekly/man-db
rm $b__etc__/cron.weekly/.placeholder
rm $b__etc__/cron.weekly/update-notifier-common

chown -R $__user__: $__backup_path__
