#!/bin/sh
echo 'update: update and autoremove softwares'
echo 'update ***: update anything including python packages'
echo 'updating sources'
sudo apt update > /dev/null
echo 'upgrading'
sudo apt -y upgrade > /dev/null
echo 'autoremoving'
sudo apt-get -y autoremove > /dev/null
echo 'upgrading python packages'
if [ $# -ne 0 ]; then
	sudo su -c 'python /home/ash/.userscripts/.pip-update.py' > /dev/null
fi
