#!/bin/bash

dir=/mnt/壁纸      #壁纸目录
cd $dir
i=0
for file in *.{jpg,png,bmp}   # 找到所有图片放入数组
do
   photos[i]=$file
   ((i++))
done

while true                          #无限循环，切换壁纸
do
   ((num=RANDOM%i))    #双小括号为运算
   gsettings set org.gnome.desktop.background picture-uri "file://$dir/${photos[$num]}"
   sleep 60
done
