#!/bin/sh

#定义位置与用户
PaperFolder=/home/ash/Pictures/Wallpapers
__user__=ash
#定义起始与终止地址
ADDRESS=$(date +%s%N)
START=1003
END=8000
PaperIndex=$((ADDRESS % ($START - $END + 1) + $START))

#内部定义
IndexPath=$PaperFolder/wallpaper-earthview-index
PaperPathTmp=$PaperFolder/background-image-temp.jpg 
PaperPath=$PaperFolder/background-image.jpg
#set the paper index randomly
if [ -r $(cat $IndexPath) ]; then
    echo $PaperIndex > $IndexPath
fi
#generate the wallpaper address
ADDRESS=$(date +%s%N)
PaperIndex=$((($(cat $IndexPath)  + $ADDRESS +1 ) % ($START - $END + 1) + $START ))
echo $PaperIndex > $IndexPath
PaperUrl=https://www.gstatic.com/prettyearth/assets/full/$((PaperIndex)).jpg
rm $PaperPathTmp
echo 'downloading...'
curl -s $PaperUrl -o $PaperPathTmp
echo 'downloaded'

if [ $(ls -l $PaperPathTmp | awk '{ print $5 }') -le 20000 ]; then
    echo 'no'
else
    echo 'y'
fi

while [ $(ls -l $PaperPathTmp | awk '{ print $5 }') -le 20000 ]; do
    ADDRESS=$(date +%s%N)
    PaperIndex=$((ADDRESS % ($START - $END + 1) + $START))
    echo $PaperIndex > $IndexPath
    echo 'no tmp wallpaper'
    PaperUrl=https://www.gstatic.com/prettyearth/assets/full/$((PaperIndex)).jpg
    curl -s $PaperUrl -o $PaperPathTmp
    echo $PaperUrl
    #sleep 1
done
#gsettings set org.gnome.desktop.background picture-uri "$PaperUrl"
#sleep 1
mv $PaperPathTmp $PaperPath	#Only change background image when a valid one has been downloaded
chown $__user__ * -R
chgrp $__user__ * -R
chmod +rw *
gsettings set org.gnome.desktop.background picture-uri "file://$PaperPath"
#gsettings set org.gnome.settings-daemon.plugins.background active true

#notify-send $PaperIndex

#XFCE4 
#case $XDG_CURRENT_DESKTOP in
#	"XFCE" )
#		for property in $(xfconf-query -c xfce4-desktop -l | grep "last-image")
#		do
#			xfconf-query -c xfce4-desktop -p $property -s ~/.background-image.jpg
#		done
#		for imagestyle in $(xfconf-query -c xfce4-desktop -l | grep "image-style")
#		do
#			xfconf-query -c xfce4-desktop -p $imagestyle -s 5
#		done
#		;;
#esac
