#!/bin/bash

# To complete the installation you must enable TLP's services (refer to the TLP FAQ):
sudo systemctl enable tlp.service
sudo systemctl enable tlp-sleep.service

# Using the Radio Device Wizard (tlp-rdw) requires an additional service:
sudo systemctl enable NetworkManager-dispatcher.service

# You should also mask the following services to avoid conflicts and assure proper operation of TLP's radio device switching options:
sudo systemctl mask systemd-rfkill.service
sudo systemctl mask systemd-rfkill.socket
