#!/bin/bash
# oh my tmux

cd
git clone https://github.com/gpakosz/.tmux.git
ln -s -f .tmux/.tmux.conf
cp .tmux/.tmux.conf.local .

echo "tmux_conf_theme_left_separator_main=''" >>~/.tmux.conf.local
echo "tmux_conf_theme_left_separator_sub=''" >>~/.tmux.conf.local
echo "tmux_conf_theme_right_separator_main=''" >>~/.tmux.conf.local
echo "tmux_conf_theme_right_separator_sub=''" >>~/.tmux.conf.local
