#!/bin/sh
echo "# History Config" > ~/.tmux.conf
echo "set-option -g history-limit 10000" >> ~/.tmux.conf
echo "" >> ~/.tmux.conf
echo "# Not see this type for my eye ^_^" >> ~/.tmux.conf
echo "# auto window rename" >> ~/.tmux.conf
echo "set-window-option -g automatic-rename" >> ~/.tmux.conf
echo "" >> ~/.tmux.conf
echo "# rm mouse mode fail" >> ~/.tmux.conf
echo "set -g default-terminal \"screen-256color\"" >> ~/.tmux.conf
echo "" >> ~/.tmux.conf
echo "# Swicth Vim model delay" >> ~/.tmux.conf
echo "set -s escape-time 0" >> ~/.tmux.conf
echo "" >> ~/.tmux.conf
echo "# Start numbering at 1" >> ~/.tmux.conf
echo "set -g base-index 1" >> ~/.tmux.conf
echo "setw -g pane-base-index 1" >> ~/.tmux.conf
echo "" >> ~/.tmux.conf
echo "# When Close Window and recount number" >> ~/.tmux.conf
echo "set -g renumber-windows on" >> ~/.tmux.conf
echo "setw -g aggressive-resize on" >> ~/.tmux.conf
echo "" >> ~/.tmux.conf
echo "" >> ~/.tmux.conf
echo "# hjkl pane traversal" >> ~/.tmux.conf
echo "bind h select-pane -L" >> ~/.tmux.conf
echo "bind j select-pane -D" >> ~/.tmux.conf
echo "bind k select-pane -U" >> ~/.tmux.conf
echo "bind l select-pane -R" >> ~/.tmux.conf
echo "" >> ~/.tmux.conf
echo "# Reload [.tmux.conf]" >> ~/.tmux.conf
echo "bind-key r source-file ~/.tmux.conf" >> ~/.tmux.conf
echo "" >> ~/.tmux.conf
echo "unbind '\"' # unbind horizontal split" >> ~/.tmux.conf
echo "unbind %   # unbind vertical split" >> ~/.tmux.conf
echo "bind-key - split-window -v # split pane horizontally" >> ~/.tmux.conf
echo "bind-key | split-window -h # split pane vertically" >> ~/.tmux.conf
echo "bind-key \ split-window -h # split pane vertically" >> ~/.tmux.conf
echo "" >> ~/.tmux.conf
echo "# List Tmux panes" >> ~/.tmux.conf
echo "bind-key Space list-panes" >> ~/.tmux.conf
echo "" >> ~/.tmux.conf
echo "# SetColor Prefix" >> ~/.tmux.conf
echo "set -g pane-border-fg green" >> ~/.tmux.conf
echo "set -g pane-active-border-fg green" >> ~/.tmux.conf
echo "" >> ~/.tmux.conf
echo "setw -g mode-keys vi" >> ~/.tmux.conf
