#!/bin/bash
echo "SHELL=/bin/bash
PATH=/usr/bin:/usr/local/bin:/bin:/home/$USER/.local/share/CharlesScripts/charles/bin


0 * * * * charles-backup
0 * * * * wallpaper-earthview
"|sudo tee -a /var/spool/cron/$USER
