#!/bin/bash
echo 'enable-rpc=true
rpc-secret=<SECRET>
rpc-allow-origin-all=true
rpc-listen-all=true
max-concurrent-downloads=15
continue=true
max-connection-per-server=16
min-split-size=10M
split=100
max-overall-download-limit=0
max-download-limit=0
max-overall-upload-limit=0
max-upload-limit=0
dir=Downloads
file-allocation=prealloc
input-file=.cache/aria2.session
save-session=.cache/aria2.session
save-session-interval=60
force-save=true'|tee $HOME/.config/aria2c.conf
$EDITOR $HOME/.config/aria2c.conf
