#!/bin/bash
export CHARLES_HOME=$HOME/.local/share/CharlesScripts/charles
export CHARLES_BACKUP=$HOME/.config/CharlesBackup

OS=$(cat /etc/issue | cut -f 1 -d ' ')
if [[ $(uname) == 'Darwin' ]]; then
    OS='Darwin'
fi
case $OS in
'Arch') INSTALL() { sudo pacman -S $@; } ;;
'Ubuntu') INSTALL() { sudo apt install $@ -y --allow-unauthenticated; } ;;
'Darwin') INSTALL() { brew install $@; } ;;
*) echo 'Your distribution has not implementd yet, please modify this command' ;;
esac
CONF_DIR=$HOME/.config/fish/conf.d
if [[ ! -d $CONF_DIR ]]; then
    mkdir -p $CONF_DIR
fi
mkdir -p ~/.cabal/bin

if [ $(which autojump | wc -l) == 0 ]; then INSTALL autojump; fi
if [ -f /usr/share/autojump/autojump.fish ];then ln -sf /usr/share/autojump/autojump.fish $CONF_DIR/autojump.fish;fi
if [ -f /usr/local/share/autojump/autojump.fish ];then ln -sf /usr/local/share/autojump/autojump.fish $CONF_DIR/autojump.fish;fi

echo "source \$HOME/.config/fish/conf.d/*" | tee -a $HOME/.config/fish/config.fish

ln -sf $CHARLES_HOME/shell.rc.d/init.fish $CONF_DIR/charles.fish

#ABBRS
fish -c "abbr ... 'cd ../..'"
fish -c "abbr autoremove 'pacman -Qtdq|xargs sudo pacman -Rsn --noconfirm'"
fish -c "abbr axel 'axel -acn50'"
fish -c "abbr c 'clear; cd'"
fish -c "abbr ccat 'ccat --bg=dark'"
fish -c "abbr cl 'cd ..;ls'"
fish -c "abbr du. 'du . --max-depth 1 -h'"
fish -c "abbr eg 'grep -E'"
fish -c "abbr emacsc 'emacs --no-window-system'"
fish -c "abbr ftps 'python3 -m http.server 8080'"
fish -c "abbr fpv fzf --preview \'ccat --color=always \{\}\'"
fish -c "abbr gaa 'git add -A'"
fish -c "abbr gb 'git branch'"
fish -c "abbr gck 'git checkout'"
fish -c "abbr gcm 'git commit -m'"
fish -c "abbr gl 'git l'"
fish -c "abbr gm 'git merge --no-ff'"
fish -c "abbr gp 'git push'"
fish -c "abbr gpl 'git pull'"
fish -c "abbr gst 'git status'"
fish -c "abbr histg 'history | grep'"
fish -c "abbr i 'ipython'"
fish -c "abbr l 'ls'"
fish -c "abbr la 'ls -a'"
fish -c "abbr le 'ls|egrep'"
fish -c "abbr lf 'ls -lah --full-time'"
fish -c "abbr lg 'ls|grep'"
fish -c "abbr ll ls++ --potsf"
fish -c "abbr lal ls++ --potsf -A"
fish -c "abbr mag2torrent 'aria2c --bt-metadata-only=true --bt-save-metadata=true'"
fish -c "abbr n 'open .'"
fish -c "abbr o 'open'"
fish -c "abbr p 'python'"
fish -c "abbr pcs 'proxychains -q'"
fish -c "abbr pdb 'python -mpowerline.bindings.pdb'"
fish -c "abbr tmux 'tmux -2'"
fish -c "abbr sshp 'ssh -o ProxyCommand=\'nc -x 127.0.0.1:1080 %h %p\''"
fish -c "abbr su 'sudo su'"

case $OS in
'Ubuntu') fish -c "abbr u 'apt-upgrade'" ;;
'Arch') fish -c "abbr u 'pacman -Syu;pacman -Rs (pacman -Qtdq)'" ;;
esac
