#!/bin/bash
git config --global core.editor "vim"
git config --global color.ui true
git config --global core.ignorecase false
git config --global core.quotepath false
git config --global color.status auto
git config --global color.diff auto
git config --global color.branch auto
git config --global color.interactive auto
git config --global alias.l "log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'"
