#!/usr/bin/env fish
#conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
#conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
#conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
#conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
conda config --set show_channel_urls yes

conda install matplotlib scikit-learn numpy sympy pandas seaborn pillow pandoc ipython jupyter requests beautifulsoup4 --yes
#conda install pytorch-cpu torchvision-cpu --yes #-c pytorch
conda install xeus-cling --yes #-c conda-forge
