#!/bin/bash
echo 'set -g MANPATH "/usr/share/man" $MANPATH' | tee ~/.config/fish/conf.d/homebrew.fish
echo 'set -g MANPATH "/usr/local/share/man" $MANPATH' | tee -a ~/.config/fish/conf.d/homebrew.fish
echo 'set -g MANPATH "/Library/Developer/CommandLineTools/usr/share/man" $MANPATH' | tee -a ~/.config/fish/conf.d/homebrew.fish
echo 'set -g MANPATH "/Library/Apple/usr/share/man" $MANPATH' | tee -a ~/.config/fish/conf.d/homebrew.fish
echo 'set -g MANPATH "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man" $MANPATH' | tee -a ~/.config/fish/conf.d/homebrew.fish
echo 'set -g fish_user_paths "/usr/local/opt/coreutils/libexec/gnubin" $fish_user_paths' | tee -a ~/.config/fish/conf.d/homebrew.fish
echo 'set -g MANPATH "/usr/local/opt/coreutils/libexec/gnuman" $MANPATH' | tee -a ~/.config/fish/conf.d/homebrew.fish
echo 'set -g fish_user_paths "/usr/local/opt/findutils/libexec/gnubin" $fish_user_paths' | tee -a ~/.config/fish/conf.d/homebrew.fish
echo 'set -g MANPATH "/usr/local/opt/findutils/libexec/gnuman" $MANPATH' | tee -a ~/.config/fish/conf.d/homebrew.fish
echo 'set -g fish_user_paths "/usr/local/opt/gnu-tar/libexec/gnubin" $fish_user_paths' | tee -a ~/.config/fish/conf.d/homebrew.fish
echo 'set -g MANPATH "/usr/local/opt/gnu-tar/libexec/gnuman" $MANPATH' | tee -a ~/.config/fish/conf.d/homebrew.fish
echo 'set -g fish_user_paths "/usr/local/opt/gnu-sed/libexec/gnubin" $fish_user_paths' | tee -a ~/.config/fish/conf.d/homebrew.fish
echo 'set -g MANPATH "/usr/local/opt/gnu-sed/libexec/gnuman" $MANPATH' | tee -a ~/.config/fish/conf.d/homebrew.fish
echo 'set -g fish_user_paths "/usr/local/opt/grep/libexec/gnubin" $fish_user_paths' | tee -a ~/.config/fish/conf.d/homebrew.fish
echo 'set -g MANPATH "/usr/local/opt/grep/libexec/gnuman" $MANPATH' | tee -a ~/.config/fish/conf.d/homebrew.fish
echo 'set -g fish_user_paths "/usr/local/opt/gawk/libexec/gnubin" $fish_user_paths' | tee -a ~/.config/fish/conf.d/homebrew.fish
echo 'set -g MANPATH "/usr/local/opt/gawk/libexec/gnuman" $MANPATH' | tee -a ~/.config/fish/conf.d/homebrew.fish
echo 'set -g fish_user_paths "/usr/local/opt/curl/bin" $fish_user_paths' | tee -a ~/.config/fish/conf.d/homebrew.fish
echo 'set -g MANPATH "/usr/local/opt/curl/share/man" $MANPATH' | tee -a ~/.config/fish/conf.d/homebrew.fish


brew tap homebrew/bundle
brew tap homebrew/cask
brew tap homebrew/cask-drivers
brew tap homebrew/cask-fonts
brew tap homebrew/command-not-found
brew tap homebrew/core

brew update
