#!/bin/sh
wget http://kdl.cc.ksosoft.com/wps-community/download/a20/wps-office_10.1.0.5444~a20_amd64.deb
sudo dpkg -i wps-office_10.1.0.5444~a20_amd64.deb
rm wps-office_10.1.0.5444~a20_amd64.deb
echo 'wget https://raw.githubusercontent.com/racaljk/hosts/master/hosts -qO /tmp/hosts && sudo sh -c cat /tmp/hosts
'>update-hosts
chmod +x update-hosts
sudo cp update-hosts /sbin/
sudo mv update-hosts /etc/cron.daily/
sudo apt-get install python-dev
sudo apt-get install transmission gedit stellarium stellarium-data elinks octave gnuplot gimp gparted emacs
sudo apt-get remove capnet-assist
gsettings set org.gnome.settings-daemon.peripherals.keyboard numlock-state on
sudo add-apt-repository ppa:simpleyyt/ppa
sudo apt-get update
sudo apt-get install noise-neteasemusic
sudo add-apt-repository ppa:ubuntu-wine/ppa
sudo add-apt-repository ppa:fcitx-team/nightly
sudo add-apt-repository ppa:plushuang-tw/uget-stable
sudo add-apt-repository ppa:launchpad.net/~blueman/+archive/ubuntu/ppa
sudo apt-get update
sudo apt-get install -y git
sudo apt-get install -y vim emacs elinks
sudo apt-get install -y goldendict
sudo apt-get install -y chromium-browser
sudo apt-get install -y build-essential
sudo apt-get install -y vlc
sudo apt-get install -y gparted
sudo apt-get install -y cmake
sudo apt-get install -y parcellite 
wget https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-beta-64-bit.deb
sudo apt-get install -y wine 
sudo dpkg -i lantern-installer-beta-64-bit.deb
 
sudo apt-get install -y docker nmon steam
rm -f lantern-installer-beta-64-bit.deb
 sudo apt-get install $(cat .install)
echo 'Dpkg::Progress-Fancy "1";' > /etc/apt/apt.conf.d/99progressbar
