#!/usr/bin/env python
import sys
import os
import subprocess
def run():
    exe = "/usr/local/scratch-text-editor"
    cwd = os.getcwd()
    cmd = [exe]
    if len(sys.argv) >= 2:
        path = sys.argv[1]
        if path.startswith("file"):
            path = path[5:]
        if not os.path.isabs(path):
            path = os.path.join(os.getcwd(), path)
        cmd = [exe, path]
    env = dict(os.environ)
    env['GTK_IM_MODULE'] = "xim"
    subprocess.Popen(cmd, env=env)
run()
