abbr a 'sudo apt-fast'
abbr c 'clear and cd'
abbr eg 'grep -E'
abbr g 'git add .; and git commit -m'
abbr i 'ipython'
abbr l 'ls --color=auto'
abbr la 'ls --almost-all --color=auto'
abbr lg 'ls --almost-all --color=auto|grep'
abbr ll 'ls --almost-all -lh --color=auto'
abbr o 'xdg-open'
abbr p 'python'
abbr s 'sudo su -'
abbr u 'update'
abbr v 'vim'
abbr x 'exit'
abbr t 'tensorboard --logdir="."'
